// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKJFXoP_G3YhJqUAbJQkQz_-FEONAre-w',
    appId: '1:738091971082:web:97d48142bccaa80509a5f3',
    messagingSenderId: '738091971082',
    projectId: 'instragram-80015',
    authDomain: 'instragram-80015.firebaseapp.com',
    storageBucket: 'instragram-80015.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdInT4hp1WTnzH6kiJSS09-gK2YTE1H24',
    appId: '1:738091971082:android:77541a2d497a09ea09a5f3',
    messagingSenderId: '738091971082',
    projectId: 'instragram-80015',
    storageBucket: 'instragram-80015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6THs1M2glfH4KU08mwyEkbqJeAQ-m6xc',
    appId: '1:738091971082:ios:67368d0b8a21bbd209a5f3',
    messagingSenderId: '738091971082',
    projectId: 'instragram-80015',
    storageBucket: 'instragram-80015.appspot.com',
    iosBundleId: 'com.example.isntragramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6THs1M2glfH4KU08mwyEkbqJeAQ-m6xc',
    appId: '1:738091971082:ios:67368d0b8a21bbd209a5f3',
    messagingSenderId: '738091971082',
    projectId: 'instragram-80015',
    storageBucket: 'instragram-80015.appspot.com',
    iosBundleId: 'com.example.isntragramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKJFXoP_G3YhJqUAbJQkQz_-FEONAre-w',
    appId: '1:738091971082:web:63c7fe8dd817811909a5f3',
    messagingSenderId: '738091971082',
    projectId: 'instragram-80015',
    authDomain: 'instragram-80015.firebaseapp.com',
    storageBucket: 'instragram-80015.appspot.com',
  );
}
